version: "2.2"
services:
  api_server:
    build: .
    ports:
    - "8080:8080"
    depends_on:
    - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    restart: always
    volumes:
      - data-docker:/data/db
  volumes:
    data-docker: