version: "3.7"
services:
  web:
    image: jfleming9357/sdc:latest
    ports:
    - "8080:8080"
    depends_on:
    - mongo
  mongo:
    image: mongo
    ports:
      - 27017:27017
    restart: always
    volumes:
       - data-docker:/data/
volumes:
  data-docker:


