version: "3.4"
services:
  web:
    build: .
    ports:
    - "3001:3001"
    depends_on:
    - mongo
  mongo:
    image: mongo
    ports:
      -27017:27017
    restart: always
    volumes:
      - data-docker:/data/db
    deploy:
      resources:
        limits:
          cpus: '0.75'
