version: "3.7"
services:
  web:
    image: jfleming9357/sdc2:latest
    ports:
    - "8080:8080"
    depends_on:
    - mongo
    environment:
    - PORT=8080
  mongo:
    image: mongo
    ports:
      - 27017:27017
    restart: always
    volumes:
       - data-docker:/data/
  redis:
    image: "redis:alpine"
    ports:
      - 6379:6379
volumes:
  data-docker:


